version: '3'
services:
  python:
    image: python:3
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html:cached
      - ./pip_modules:/pip_modules
    environment:
      - PYTHONIOENCODING=utf-8
      - LANG=C.UTF-8
      - PYTHONUSERBASE=/pip_modules

